/// Raw FFI bindings generated by bindgen from codec.h.
#[allow(non_upper_case_globals, non_camel_case_types, non_snake_case, dead_code)]
pub(crate) mod sys {
    include!(concat!(env!("OUT_DIR"), "/codec_bindings.rs"));
}

use barq_types::{BarqError, BarqResult};

/// Compress `data` using LZMA at the given level (1–9).
pub fn compress_lzma(data: &[u8], level: u32) -> BarqResult<Vec<u8>> {
    let bound = unsafe { sys::barq_estimate_lzma_bound(data.len()) };
    let mut out = vec![0u8; bound];
    let mut out_len = bound;

    let rc = unsafe {
        sys::barq_compress_lzma(
            data.as_ptr(),
            data.len(),
            out.as_mut_ptr(),
            &mut out_len,
            level,
        )
    };

    if rc != 0 {
        return Err(BarqError::Compression(
            "LZMA compression failed".to_string(),
        ));
    }

    out.truncate(out_len);
    Ok(out)
}

/// Decompress LZMA-compressed `data`.
///
/// `hint_original_size` is used as the initial output buffer size.
/// The buffer is doubled and retried on overflow up to 3 times.
pub fn decompress_lzma(data: &[u8], hint_original_size: usize) -> BarqResult<Vec<u8>> {
    let mut buf_size = hint_original_size.max(data.len() * 4);

    for _ in 0..3 {
        let mut out = vec![0u8; buf_size];
        let mut out_len = buf_size;

        let rc = unsafe {
            sys::barq_decompress_lzma(
                data.as_ptr(),
                data.len(),
                out.as_mut_ptr(),
                &mut out_len,
            )
        };

        if rc == 0 {
            out.truncate(out_len);
            return Ok(out);
        }

        // Retry with a larger buffer
        buf_size *= 2;
    }

    Err(BarqError::Compression(
        "LZMA decompression failed (buffer overflow after retries)".to_string(),
    ))
}
